INSERT INTO [dbo].[Employee] ([Id], [AddressId], [PersonId], [CompanyName], [Position], [EmployeeName])
VALUES
(1, 1, 1, 'London Apparel', 'Manager', 'John Doe'),
(2, 2, 2, 'Bluebird Systems', 'Developer', 'Jane Smith'),
(3, 3, 3, 'Silver Finances', 'Analyst', 'Michael Johnson'),
(4, 4, 4, 'Dreamland Innovations', 'Engineer', 'Sarah Brown'),
(5, 5, 5, 'Peoria Studios', 'Photographer', 'Jessica Taylor'),
(6, 6, 6, 'Golden Star Builders', 'Architect', 'Jacob Miller'),
(7, 7, 7, 'Eagle Eye Law', 'Lawyer', 'Mohammed Anderson'),
(8, 8, 8, 'Prestige Motors', 'Engineer', 'Emily Thomas'),
(9, 9, 9, 'Advanced Health', 'Doctor', 'Joshua Jackson'),
(10, 10, 10, 'Aurora Publishers', 'Editor', 'Amanda White'),
(11, 11, 11, 'Jungle Foods', 'Product Manager', 'Andrew Harris'),
(12, 12, 12, 'California Solar', 'Engineer', 'Anna Martin'),
(13, 13, 13, 'Kingdom Real Estate', 'Realtor', 'Oliver Thompson'),
(14, 14, 14, 'West Coast Sports', 'Coach', 'Patricia Garcia'),
(15, 15, 15, 'Lighthouse Academics', 'Teacher', 'Jack Martinez'),
(16, 16, 16, 'Standard Investments', 'Broker', 'Laura Robinson'),
(17, 17, 17, 'Broadway Entertainment', 'Actor', 'Matthew Clark'),
(18, 18, 18, 'International Cuisine', 'Chef', 'Rebecca Rodriguez'),
(19, 19, 19, 'Skylark Hotels', 'Manager', 'Chris Lewis'),
(20, 20, 20, 'Boston Marine', 'Captain', 'Jennifer Walker'),
(21, 21, 21, 'Harmony Music', 'Musician', 'Daniel Hall'),
(22, 22, 22, 'Noble Jewelry', 'Salesperson', 'Linda Young'),
(23, 23, 23, 'Redstone Games', 'Designer', 'Thomas Allen'),
(24, 24, 24, 'Gotham Security', 'Security Guard', 'Nancy King'),
(25, 25, 25, 'Bayside Insurance', 'Insurance Agent', 'Paul Scott'),
(26, 26, 26, 'Old Town Prints', 'Artist', 'Susan Wright'),
(27, 27, 27, 'Express Delivery', 'Courier', 'Kevin Lopez'),
(28, 28, 28, 'Emerald Gardens', 'Gardener', 'Karen Hill'),
(29, 29, 29, 'Rapid Repairs', 'Plumber', 'Brian Thomas'),
(30, 30, 30, 'Florida Designs', 'Designer', 'Megan Adams');